### PR TITLE
Fix destroy() issues

### LINKED ISSUE #5: destroy() discussion with partial fix
I noticed the `destroy()` method needs to be updated slightly to work correctly:
```js
destroy() {
    const gl = this.gl // moved to top of function
    this.stop() // cancel raf and prevent bind calls on deleted buffers
    // ... rest of function
}
```
The above works fine if you call `sd.destroy()` immediately after `sd.start()`, however, I didn't submit as a patch because there are some related issues that I wasn't sure how to elegantly address.

If you were to call destroy _before_ start in the first demo, you get WebGL warnings for "attempt to bind a deleted buffer". Makes sense, and resolved by adding a `this.gl.isBuffer(this.positionBuffer)` check before enqueuing update, but I'm trying to think of a good edge case that would need this. Perhaps this is just a monkey bug.

Textures also need some considerations when destroying. If destroy is called before the internal onload, self.update() will try to bind deleted textures. Better to refactor the onload listener so it can be removed in destroy, or add a check for `this.gl.isTexture(this.texture)` before updating?

### PR DESCRIPTION
**Pull request by nikrowell**
(Fixes #5) Not necessarily crazy about exposing the `onLoad` method on the Texture class, but perhaps not a big deal - let me know if you had something else in mind!

### CODE REVIEW

**Comment by ayamflow** [comment]
Thanks for putting more time into this small lib ☺️
I have 2 questions/suggestions!
- instead of exposing the `Texture.onLoad()`,  you can just make it a private function (just like isPoweOfTwo and getProp) and use `Function.call` to pass the scope down to it.
- Why testing `gl.isBuffer(this.positionBuffer)` in the `start()` method rather than in the destroy? As I see it, if the test fails because the user is calling `.start()` on a destroyed instance, it will fail silently. However, what we want instead (if I'm getting this correctly) is just to prevent erroring when deleting a buffer that doesn't exist. If the user calls `start()` on a destroyed shader, it should throw an error because that's not an expected behavior.

**Comment by nikrowell** [comment]
> make it a private function (just like isPoweOfTwo and getProp) and use `Function.call` to pass the scope down to it.

Good call, I'll update.

> Why testing `gl.isBuffer(this.positionBuffer)` in the `start()` method rather than in the destroy? As I see it, if the test fails because the user is calling `.start()` on a destroyed instance, it will fail silently. However, what we want instead (if I'm getting this correctly) is just to prevent erroring when deleting a buffer that doesn't exist. If the user calls `start()` on a destroyed shader, it should throw an error because that's not an expected behavior.

I think the issue was because if you call `destroy()` before `start()` (back button example with animated transition), start will enqueue `update()`, which will then attempt to bind deleted buffers. Perhaps I'm missing something though - and simply calling `destroy()` before `start()` in the same frame / event loop is a monkey bug...

> Thanks for putting more time into this small lib

Thanks for letting me contribute and for the feedback! Love the simplicity and am considering testing this as a very lightweight 2d shader for a few potential projects.

**Comment by nikrowell** [comment]
Actually... not sure how to implement the private function approach when we also need to reference the bound version with `removeEventListener` in `destroy()`

**Comment by ayamflow** [comment]
Ah, you're right... I guess public it is.

Thanks for the explanation. I think the only trap I can see is that calling start with deleted buffer will be silent - do you think we should either `throw` or `console.warn/error` some kind of message to the user?

**Comment by nikrowell** [comment]
Good point. Perhaps this is too much of an edge case and we just remove the extra isBuffer checks for now?

**Comment by ayamflow** [comment]
I'm good with that :)

**Comment by nikrowell** [comment]
Updated to remove the `isBuffer` check in `start()`, but found that I needed to prevent a texture from calling `update()` if it's parent shader has been destroyed. 

Example in demo 3 where the `onload` calls `sd3.uniforms.canvas.update()`. I'm simply setting update to an empty function, but open to other ideas (the internal needsUpdate flag could be an opportunity to refactor this).

**Comment by ayamflow** [comment]
👍 awesome! Thanks a lot

**Pull request merged**
